# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Description of policy')),
                ('object_id', models.PositiveIntegerField()),
                ('anonymous', models.BooleanField(default=False, help_text=b'Apply this policy to anonymous users?')),
                ('authenticated', models.BooleanField(default=False, help_text=b'Apply this policy to authenticated users?')),
                ('apply_to_owners', models.BooleanField(default=False, help_text=b'Apply this policy to owners of content objects?')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text=b'Apply this policy for these user groups.', to='auth.Group')),
                ('permissions', models.ManyToManyField(blank=True, help_text=b'Permissions granted by this policy', related_name='permissions', to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'permissions': (('view_policy', 'Can view policy'),),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='Description of intended use')),
                ('permissions', models.ManyToManyField(blank=True, help_text=b'Specific permissions for this role.', to='auth.Permission')),
            ],
            options={
                'permissions': (('view_role', 'Can view role'), ('manage_role_permissions', 'Can manage role permissions'), ('manage_role_users', 'Can manage role users')),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of intended use')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_team', 'Can view team'),),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Team'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, help_text=b'Users granted this role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='team',
            field=models.ForeignKey(blank=True, help_text=b'Team responsible for managing this policy', null=True, on_delete=django.db.models.deletion.CASCADE, to='teamwork.Team'),
        ),
        migrations.AddField(
            model_name='policy',
            name='users',
            field=models.ManyToManyField(blank=True, help_text=b'Apply this policy for these users.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('name', 'team')]),
        ),
    ]
